# Generated by Django 4.1.3 on 2023-02-24 10:25

from django.contrib.auth.models import Group
from django.db import migrations


def add_groups(apps, schema_editor):
    Group(name='Patient').save()
    Group(name='Nurse').save()
    Group(name='Admin').save()


def add_patients(apps, schema_editor):
    user_model = apps.get_model('account', 'User')
    group_model = apps.get_model("auth.Group")
    
    g = group_model.objects.get(name='Patient')
    
    u = user_model(username='patient1', first_name='John', last_name='Smith')   
    u.save()
    u.groups.add(g)

    u = user_model(username='patient2', first_name='Sarah', last_name='Dixon')
    u.save()
    u.groups.add(g)
    
    
class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups),
        migrations.RunPython(add_patients),
    ]
