# Generated by Django 4.1.3 on 2023-02-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(0, 'Boolean'), (1, 'Integer'), (2, 'Float')], default=0)),
                ('operator', models.PositiveSmallIntegerField(choices=[(0, '<'), (1, '>'), (2, '=')], default=2)),
                ('value', models.CharField(default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('node_type', models.PositiveSmallIntegerField(choices=[(0, 'Leaf'), (1, 'Non Leaf')], default=1)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.condition')),
                ('neg_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='decisions.node')),
                ('pos_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='decisions.node')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
    ]
