# Generated by Django 4.1.3 on 2023-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='value_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
