# Generated by Django 4.1.3 on 2023-02-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_condition_value_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='neg_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='decisions.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='pos_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='decisions.node'),
        ),
    ]
