# Generated by Django 4.1.3 on 2023-02-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_alter_node_neg_node_alter_node_pos_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decisions.condition'),
        ),
    ]
