# Generated by Django 4.1.3 on 2023-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_alter_node_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Decision Tree',
                'verbose_name_plural': 'Decision Trees',
            },
        ),
    ]
