# Generated by Django 4.1.3 on 2023-02-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0006_decisiontreenodem2m_decisiontree_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='neg_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='pos_node',
        ),
    ]
