# Generated by Django 4.1.3 on 2023-02-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decisions', '0009_alter_decisiontreenodem2m_decision_tree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTreeRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='', max_length=64)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.decisiontree')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decision Tree Run',
                'verbose_name_plural': 'Decision Tree Runs',
            },
        ),
    ]
