# Generated by Django 4.1.3 on 2023-02-24 09:09

from django.db import migrations
from haelu.enums import VALUE_TYPE_INTEGER, VALUE_TYPE_BOOLEAN


def fill_markers(apps, schema_editor):
    marker_model = apps.get_model('markers', 'Marker')
    marker_model(name='age', value_type=VALUE_TYPE_INTEGER, unit='years').save()
    marker_model(name='urine infection', value_type=VALUE_TYPE_BOOLEAN, unit='').save()
    marker_model(name='systolic bp', value_type=VALUE_TYPE_INTEGER, unit='mmHg').save()
    marker_model(name='mental state concern', value_type=VALUE_TYPE_BOOLEAN, unit='').save()


def add_example_results(apps, schema_editor):
    user_model = apps.get_model('account', 'User')
    marker_model = apps.get_model('markers', 'Marker')
    marker_result_model = apps.get_model('markers', 'MarkerResult')

    marker_age = marker_model.objects.get(name='age')
    marker_urine = marker_model.objects.get(name='urine infection')
    marker_systolic_bp = marker_model.objects.get(name='systolic bp')
    marker_mental = marker_model.objects.get(name='mental state concern')

    p1 = user_model.objects.get(username='patient1')
    marker_result_model(patient=p1, marker=marker_age, result=25).save()
    marker_result_model(patient=p1, marker=marker_urine, result=True).save()
    marker_result_model(patient=p1, marker=marker_systolic_bp, result=55).save()
    marker_result_model(patient=p1, marker=marker_mental, result=False).save()

    p2 = user_model.objects.get(username='patient2')
    marker_result_model(patient=p2, marker=marker_age, result=76).save()
    marker_result_model(patient=p2, marker=marker_urine, result=True).save()
    marker_result_model(patient=p2, marker=marker_systolic_bp, result=45).save()
    marker_result_model(patient=p2, marker=marker_mental, result=True).save()


class Migration(migrations.Migration):
    dependencies = [
        ('markers', '0001_initial'),
        ('account', '0002_add_groups_and_users'),
    ]

    operations = [
        migrations.RunPython(fill_markers),
        migrations.RunPython(add_example_results),
    ]
