# Generated by Django 4.1.3 on 2023-02-24 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_filldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerresult',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marker',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
