VALUE_TYPE_BOOLEAN = 0
VALUE_TYPE_INTEGER = 1
VALUE_TYPE_FLOAT = 2

VALUE_TYPE_CHOICES = (
    (VALUE_TYPE_BOOLEAN, 'Boolean'),
    (VALUE_TYPE_INTEGER, 'Integer'),
    (VALUE_TYPE_FLOAT, 'Float'),
)

OPERATOR_LESS_THAN = 0
OPERATOR_GREATER_THAN = 1
OPERATOR_EQUAL_TO = 2

OPERATOR_CHOICES = (
    (OPERATOR_LESS_THAN, '<'),
    (OPERATOR_GREATER_THAN, '>'),
    (OPERATOR_EQUAL_TO, '='),
)
